@startuml
张三 ->] : 我要借钱
activate 张三

[--> 张三 : 风险有点大，有担保吗？
activate 张三 #FFBBBB

张三 -> 张三 : 我来虚拟个担保人

[--> 张三 : 借给你
deactivate 张三

张三 ->] : 我要还钱
[--> 张三 : 收到欠款


张三 ->] : 我还要借钱
[--> 张三 : 不借了
deactivate 张三

@enduml